#!/bin/bash
#__author__: newtorn
#create_time: 2019/05/20

YesOrNo(){
    read -p "$1[Y/N]? " yn
    while true; do
        case $yn in
            [Yy]|[Yy][Ee][Ss] )
                return 0
                ;;
            [Nn]|[Nn][Oo] )
                return 1
                ;;
            * )
                echo -n "Please type yes or no: "
                read yn
                ;;
        esac
    done
}

Usage(){
    echo "
    Example usage:
        newgo init
        newgo help
        newgo unset
        newgo run src/entry/hello.go
        newgo build src/entry/hello.go
        newgo install src/entry/hello.go

    Further help:
        newgo commands
        newgo help [COMMAND]
        man newgo
    "
}

Init(){
    echo "Initializing `pwd` to $HOME ..."
    if [ ! -f $HOME/.newgo ];then
        echo "Touching file \".newgo\" to $HOME ..."
        touch $HOME/.newgo
        echo 'Okay, file ".newgo" has been created!'
    else
        echo 'Skip, file ".newgo" has been existed!'
    fi
    for fd in src pkg bin; do
        if [ ! -d `pwd`/$fd ];then
            mkdir `pwd`/$fd
            echo "Created floder ${fd} to project!"
        else
            echo "Skip, floder ${fd} has been existed!"
        fi
    done
    echo 'project='`pwd` > $HOME/.newgo
    echo 'Successfuly, please use command `newgo` instead of `go`!'
}

Unset() {
    if YesOrNo "Unset newgo enviroment in `pwd` "; then
        echo 'Removing newgo environment...'
        rm -rf $HOME/.newgo
        echo "Deleted file \".newgo\" in $HOME ..."
        for fd in src pkg bin; do
            rm -rf `pwd`/$fd
            echo "Deleted floder ${fd} in project!"
        done
        echo 'Successfully, please use command `newgo init` to init again!'
    else
        echo 'Discarded unset operation!'
    fi
}

GoCMD(){
    if [ ! -f $HOME/.newgo ];then
        echo 'Notice, file ".newgo" has not been created!'
        echo 'Use command `newgo init` in your project root to init!'
    else
        inifile="$HOME/.newgo"
        pro=`sed '/^project=/!d;s/.*=//' $inifile`
        if [[ "`pwd`" == $pro* ]];then
            if [ ! -d $pro ];then
                echo 'Project \"'$pro'\" does not exists!'
            else
                export GOPATH=$pro
                export GOBIN=$pro/bin
                go $*
            fi
        else
            echo 'You are using newgo command out of actived project!'
            echo 'Please use command `go` or `newgo init` here as project!'
        fi
    fi
}


# START MAIN-OPTIONS
case $1 in
    help) Usage ;;
    init) Init ;;
    unset) Unset ;;
    *) GoCMD $* ;;
esac
# END MAIN-OPTIONS
